services:
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: mood-tracker-frontend
    ports:
      - "3000:3000" # Next.js
    volumes:
      - ./frontend:/app
      - /app/node_modules # avoid overwriting node_modules with host's empty folder
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # helps with hot reload in Docker
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      db:
        condition: service_healthy

  backend-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: springboot-backend-dev
    ports:
      - "8081:8080"
    volumes:
      - ./backend/src:/app/src
      - ./backend/build.gradle:/app/build.gradle
      - ~/.gradle:/home/gradle/.gradle # Cache gradle dependencies
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  # storybook:
  #   build: .
  #   container_name: storybook-dev
  #   ports:
  #     - "6006:6006"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - WATCHPACK_POLLING=true
  #   command: npm run storybook -- --no-open

volumes:
  pgadmin_data:
